name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
      - name: Create HTML page to embed PDF
        run: |
          echo '<html><body><iframe src="./document.pdf" width="100%" height="100%"></iframe></body></html>' > index.html
      - name: Deploy to GitHub Pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch
          git checkout gh-pages
          git rm -rf .
          cp main.pdf ./document.pdf
          cp index.html ./index.html
          git add ./document.pdf ./index.html
          git commit -m "Update PDF and HTML"
          git push origin gh-pages
